[project]
authors = ["Loic Gouarin <loic.gouarin@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "animations"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
manim = ">=0.18.1,<0.19"
