name: GitHub Pages Deploy
on:
    push:
        branches: [main]
env:
    BASE_URL: /${{ github.event.repository.name }}

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false
jobs:
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup Pages
              uses: actions/configure-pages@v3
            - name: Render Book project
              uses: quarto-dev/quarto-actions/render@v2
              with:
                  to: html
            - name: Publish HTML book
              uses: quarto-dev/quarto-actions/publish@v2
              with:
                  target: gh-pages
                  render: false
